#!/usr/bin/env bash
# Bash script that Install nginx on your web-01 server and requirements
apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/log/html/index.html
service nginx start
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/log/html;
     index       index.html index.htm;
}
" > /var/log/sites-available/default

service nginx restart