#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /var/nginx/html
sudo touch /var/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/nginx/html;
     index       index.html index.htm;
}
" > /var/nginx/sites-available/default

sudo service nginx start
